# Generated by Django 3.2.15 on 2022-08-23 18:54

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomec', models.CharField(max_length=200)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('mit_bal', models.IntegerField()),
                ('sex', models.PositiveSmallIntegerField()),
                ('education', models.PositiveSmallIntegerField()),
                ('marriage', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('pay_1', models.SmallIntegerField()),
                ('pay_2', models.SmallIntegerField()),
                ('pay_3', models.SmallIntegerField()),
                ('pay_4', models.SmallIntegerField()),
                ('pay_5', models.SmallIntegerField()),
                ('pay_6', models.SmallIntegerField()),
                ('bill_amt_1', models.IntegerField()),
                ('bill_amt_2', models.IntegerField()),
                ('bill_amt_3', models.IntegerField()),
                ('bill_amt_4', models.IntegerField()),
                ('bill_amt_5', models.IntegerField()),
                ('bill_amt_6', models.IntegerField()),
                ('pay_amt_1', models.IntegerField()),
                ('pay_amt_2', models.IntegerField()),
                ('pay_amt_3', models.IntegerField()),
                ('pay_amt_4', models.IntegerField()),
                ('pay_amt_5', models.IntegerField()),
                ('pay_amt_6', models.IntegerField()),
                ('payment', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
